---

- name: Check if admin password written by system
  stat:
    path: "{{ nexus_data_dir }}/admin.password"
  register: password_file

- name: Change the admin user password
  uri:
    url: "http://localhost:{{ nexus_default_port }}{{ nexus_default_context_path }}service/rest/beta/security/users/admin/change-password"
    user: 'admin'
    password: "{{ lookup('file', nexus_data_dir + '/admin.password') }}"
    body: 
      type: "text/plain"
      content: "{{ current_nexus_admin_password }}"
    method: PUT
    force_basic_auth: yes
    status_code: 204,404
    headers:
      Content-Type: "text/plain"
  when: password_file.stat is defined and password_file.stat.exists

