---
- name: Copy httpd vhost
  template:
    src: "nexus-vhost.conf"
    dest: "/etc/httpd/conf.d"
  notify:
    - httpd-service-reload
    - wait-for-httpd

- name: Copy SSL certificate file
  copy:
    src: "{{ httpd_ssl_certificate_file }}"
    dest: "/etc/pki/tls/certs"
    mode: 600
  notify:
    - httpd-service-reload
    - wait-for-httpd

- name: Copy SSL certificate key file
  copy:
    src: "{{ httpd_ssl_certificate_key_file }}"
    dest: "/etc/pki/tls/private"
    mode: 600
  notify:
    - httpd-service-reload
    - wait-for-httpd

- name: Setsebool httpd_can_network_connect
  shell: 'setsebool -P httpd_can_network_connect on'

- meta: flush_handlers
