---
- name: "Run restoration script"
  shell: "nexus-blob-restore.sh {{ nexus_restore_point }} 2>&1 | tee -a {{ nexus_restore_log }}"
  notify:
    - nexus-service-restart
    - wait-for-nexus
    - wait-for-nexus-port

- meta: flush_handlers
