---
- name: Make sure nexus is stopped
  debug:
    msg: "trigger nexus stop"
  changed_when: true
  notify:
    - nexus-service-stop

- meta: flush_handlers

- name: "Make sure an other nexus install is not running"
  service:
    name: nexus
    state: stopped

- name: "Purge Nexus"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ nexus_data_dir }}"
  - "{{ nexus_installation_dir }}/nexus-{{ nexus_version }}"
  - "{{ nexus_restore_log }}"
# - "{{ nexus_backup_dir }}" # Optional

- name: "remove nexus package if present"
  package:
    name: nexus
    state: absent
